apiVersion: v1
kind: Service
metadata:
  labels:
    app: khealth
  name: khealth
spec:
  ports:
    - port: 8080
      targetPort: rcscheduler
      nodePort: 31337
  type: NodePort
  selector:
    app: khealth
    role: master


