apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: khealth
    role: master
  name: khealth
spec:
  replicas: 1
  selector:
    app: khealth
    role: master
  template:
    metadata:
      labels:
        app: khealth
        role: master
    spec:
      containers:
          - image: quay.io/coreos/khealth
            name: rcscheduler
            command:
              - "rcscheduler"
            ports:
            - containerPort: 8080
              name: rcscheduler

